site_name: Open Creator
site_url: https://open-creator.github.io
repo_url: https://github.com/timedomain-tech/open-creator
repo_name: open-creator
nav:
  - Getting Start:
    - Overview: index.md
    - Installation: installation.md
  - Examples:
    - 01 Skills Create: examples/01_skills_create.ipynb
    - 02 Skills Lirabry: examples/02_skills_library.ipynb
    - 03 Skills Search: examples/03_skills_search.ipynb
    - 04 Skills Run: examples/04_skills_run.ipynb
    - 05 Skills Test: examples/05_skills_test.ipynb
    - 06 Skills Refactor: examples/06_skills_refactor.ipynb
    - 07 Skills Auto Optimize: examples/07_skills_auto_optimize.ipynb
    - 08 Creator Agent: examples/08_creator_agent.ipynb
  - API:
    - API Docs: api_doc.md
    - Commands: commands.md
    - Configurations: configurations.md

theme: 
  name: material
  logo: pics/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  features:
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - content.tabs.link
      - header.autohide
      - announce.dismiss
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
      - navigation.expand
      - search
      - search.suggest
      - search.highlight
      - search.share

plugins:
  - search
  - mkdocs-jupyter:
      kernel_name: python3
      ignore_h1_titles: true
      include_requirejs: true
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
